Vagrant.configure("2") do |config|
  # config.vm.box = "ubuntu/jammy64" # no vmware support
  config.vm.box = "generic/ubuntu2204"
  
  config.vm.provision "shell", inline:<<-EOF
    sudo apt update -y
	sudo apt install ubuntu-desktop
  EOF
  
  config.trigger.after [:provision] do |t|
    t.name = "Reboot after provisioning"
    t.run = { :inline => "vagrant reload" }
  end
end