Vagrant.configure("2") do |config|
  # config.vm.box = "ubuntu/jammy64" # no vmware support
  config.vm.box = "generic/ubuntu2204"
  
  config.vm.provision "shell", reboot: true, inline:<<-EOF
    sudo apt update -y
    sudo apt install -y ubuntu-desktop open-vm-tools-desktop
  EOF
end