Vagrant.configure("2") do |config|
  # config.vm.box = "ubuntu/jammy64" # no vmware support
  config.vm.box = "generic/ubuntu2204"
  
  config.vm.provider :virtualbox do |v|
    #v.gui = true
    #v.memory = 8096
    #v.cpus = 4
    v.customize ['modifyvm', :id, '--accelerate3d', 'on']
    # This is commented out until resolution has been found for proper
    # usage. For now it will use the default graphics controller.
    v.customize ['modifyvm', :id, '--graphicscontroller', 'vmsvga']
    # v.customize ['modifyvm', :id, '--graphicscontroller', 'vboxvga']
    v.customize ['modifyvm', :id, '--hwvirtex', 'on']
    v.customize ['modifyvm', :id, '--ioapic', 'on']
    v.customize ['modifyvm', :id, '--vram', '256']
    v.customize ['modifyvm', :id, '--audio', 'none']
  end
  
   # Update repositories
  config.vm.provision :shell, inline: "sudo apt update -y"

  # Upgrade installed packages
  config.vm.provision :shell, inline: "sudo apt upgrade -y"

  # Add desktop environment
  config.vm.provision :shell, inline: "sudo apt install -y --no-install-recommends ubuntu-desktop"
  config.vm.provision :shell, inline: "sudo apt install -y --no-install-recommends open-vm-tools-desktop"
  
  # Restart
  config.vm.provision :shell, inline: "sudo shutdown -r now"
end
